let date = new Date()
console.log(date)
console.log(date.toString())
console.log(date.toDateString())
console.log(date.getDate())
console.log(date.getFullYear())
console.log(date.toLocaleTimeString())
console.log(date.toISOString())
console.log(date.toJSON())
console.log(date.toLocaleString())

let myTimeStamp = Date.now()
console.log(myTimeStamp)
console.log(Math.floor(Date.now()/1000))